Part 1: Primer

1: Lists

In [1]:
import pandas as pd
import numpy as np

1) Make a list with the spelled-out number strings ‘one’, ‘two’, ‘three’, ‘four’, and ‘five’
in that order and call it myList.

In [2]:
mylist = ["one", "two", "three", "four", "five"]
print(mylist)

['one', 'two', 'three', 'four', 'five']


2) Remove ‘three’ from the list using positional indexing.

In [3]:
mylist = ["one", "two", "three", "four", "five"]
del mylist[2]
print(mylist)

['one', 'two', 'four', 'five']


3) Check if ‘four’ is in the list.

In [4]:
mylist = ["one", "two", "three", "four", "five"]
if "four" in mylist:
    print("yes, four found in the list")
else:
    print("no, four is not found in the list")

yes, four found in the list


4) Append ‘six’ to the end of the list, then print the length of the list.

In [5]:
mylist = ["one", "two", "three", "four", "five"]
mylist.append("six")
len(mylist)

6

5) Print the contents of the list, but also next to each item print the length of the string 
(e.g. one is 3, four is 4) using a for loop.

In [6]:
for entry in mylist:
        l = len(entry)
        print("Length of", entry, "is", l)

Length of one is 3
Length of two is 3
Length of three is 5
Length of four is 4
Length of five is 4
Length of six is 3


6) Create a list only of the lengths of the strings and show your result.
You can use the loop before to fill the list.

In [7]:
mylist = ["one", "two", "three", "four", "five"]
newlist=[]
for element in mylist:
    newlist.append(len(element))
print(newlist)

[3, 3, 5, 4, 4]


2: Dictionaries

1) Make a dictionary with the keys English words as below, and the values be the translation. You can use this language example (German) or choose your own. Note: you need to make sure all of these words are represented as strings, in quotes.
apple - Apfel
apples - Äpfel
I - Ich
and - und
like - mag
strawberries - Erdbeeren

In [8]:
dict = {'apple' : 'Apfel', 'apples' : 'Äpfel', 'I' : 'Ich', 'and' : 'und', 'like' : 'mag', 'strawberries' : 'Erdbeeren'}
print(dict)

{'apple': 'Apfel', 'apples': 'Äpfel', 'I': 'Ich', 'and': 'und', 'like': 'mag', 'strawberries': 'Erdbeeren'}


2) Use the dictionary to look up the translation for ‘apple’ and ‘like’.

In [28]:
print(dict.get("apple"))
print(dict["like"])

Apfel
mag


3) Make a variable var with the string “I like apples and strawberries”.

In [10]:
var = "I like apples and strawberries"
print(var)

I like apples and strawberries


4) Now create a list from var with each word a separate item (this is a string split operation).

In [11]:
newlist=var.split(" ")
print(newlist)

['I', 'like', 'apples', 'and', 'strawberries']


5) Iterate through the list you’ve created and replace any word in your dictionary with the translation.

In [12]:
for i in range(len(newlist)):
    newlist[i] = dict.get(newlist[i])
print(newlist)

['Ich', 'mag', 'Äpfel', 'und', 'Erdbeeren']


6) Now take your new list and turn it into a string with spaces between the words.

In [13]:
print(" ".join(newlist))

Ich mag Äpfel und Erdbeeren


3: Arrays

1) Create an array of zeros of size 8 x 8 and print the data type of the array.

In [14]:
arr = np.zeros((8,8))
print(arr)
print(arr.dtype)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
float64


2) Fill the array with the numbers 1 to 64 first by row, then by column. 
You may want to use a for loop inside a for loop to do this.

In [15]:
# define range of matrix columns and rows
n = 8

#loop to iterate over array to fill values
for i in range(n):
    for j in range(n):
        if i==0 and j==0:
            arr[i,j]=1
        elif i<j:
            arr[:,j]=arr[:,j-1]+1
        elif j<i:
            arr[i,:]=arr[i-1,:]+n
print(arr)       

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]


3) Transpose the array.

In [16]:
#transpose of array
arr_transpose = arr.transpose()
print(arr_transpose)

[[ 1.  9. 17. 25. 33. 41. 49. 57.]
 [ 2. 10. 18. 26. 34. 42. 50. 58.]
 [ 3. 11. 19. 27. 35. 43. 51. 59.]
 [ 4. 12. 20. 28. 36. 44. 52. 60.]
 [ 5. 13. 21. 29. 37. 45. 53. 61.]
 [ 6. 14. 22. 30. 38. 46. 54. 62.]
 [ 7. 15. 23. 31. 39. 47. 55. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64.]]


4) Print only the top 4 rows and columns.

In [17]:
#print 4 rows and columns of array
print(arr[0:4,0:4])

[[ 1.  2.  3.  4.]
 [ 9. 10. 11. 12.]
 [17. 18. 19. 20.]
 [25. 26. 27. 28.]]


5) Make a 1D array out of your 2D array with the numbers 1 to 64 in order 
(note the column vs row issue, you may need transposes.)

In [18]:
#reshape the array into 1D
arr_1D = arr.flatten()

print(arr_1D)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54.
 55. 56. 57. 58. 59. 60. 61. 62. 63. 64.]


6) Now take that 1D array you made from before and reshape it back to the original 2D array.

In [19]:
#reshape 1D to 2D
arr_2D = arr_1D.reshape(8,8)
print(arr_2D)

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]


Part 2: Applications

1. Word Counts

Word counts are often used in text processing to automatically classify documents by topic. They are also used to automatically measure the “sentiment” by counting, for example, the number of positive or negative words used in the comment or essay. Write code to count the number of unique words in a very large string using the following steps.

a)First convert the string to a list with each word a separate item in the list. Hint: use a string split function for your language, and make sure it separates by “ ”. 


In [29]:
#split string to list
strng = input("Enter the string:")

strlist = strng.split(" ")

print(strlist)

Enter the string:Can you can a can as a canner can can a can
['Can', 'you', 'can', 'a', 'can', 'as', 'a', 'canner', 'can', 'can', 'a', 'can']


b)Then use a dictionary to associate each word with a count. Note, the dictionary won’t be able to increment a key unless you add it first, so you may have to check to see if it exists before setting the original count of a word to 1. 


In [30]:
#create dictonary with words and count
word_dict={}
for i in range(len(strlist)):
    word_dict[strlist[i]]=strlist.count(strlist[i])
       
print(word_dict)  

{'Can': 1, 'you': 1, 'can': 5, 'a': 3, 'as': 1, 'canner': 1}


c)Print each word and its count afterwards, and test with an interesting block of text that will have multiple words counted multiple times. (Note, the words don’t have to be in any particular order.)


In [22]:
#display output of string and count using series
pd.Series(word_dict)

Can       1
you       1
can       5
a         3
as        1
canner    1
dtype: int64

2. Adding an Array Border

As we will see later in the class, arrays can be used to represent images. In particular, black and white images can be represented by a 2D array, with one number (usually 0) representing black and another number (usually 1, but sometimes something else) representing white, and gray being everything in between. Here we just want to test your ability to handle a 2D array and add a border (filled with 0's) around it. In code this means creating an array of 0’s of width+2 by height+2 size and copying the original array into the middle appropriately (Note: do not use np.pad() function).


Test with an array in the center that has non-zero elements. First print the original array, then print the new array with the added border of 0’s. For example:
Expected Output:

Original array: 
[[ 1 1 1 1 ] 
 [ 1 1 1 1 ] 
 [ 1 1 1 1 ]] 

New array (0 on the border and 1 inside in the array): 
[[ 0 0 0 0 0 0 ] 
 [ 0 1 1 1 1 0 ] 
 [ 0 1 1 1 1 0 ] 
 [ 0 1 1 1 1 0 ] 
 [ 0 0 0 0 0 0 ]]


In [23]:
#create a 3*3 matrix of ones
arr_original = np.ones((3,3))
arr_original

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
#Padding zeros to a matrix using hstack and vstack functions
horizantal = np.zeros((3,1))
vertical = np.zeros((1,5))

np.vstack([np.vstack([vertical,np.hstack([np.hstack([horizantal,arr_original]),horizantal])]),vertical])

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

3. Functions

Encapsulate the previous code into functions. The first function word_count(text) prints each word and its count of text. The second function add_border(array) prints the original array and the new array with the added border of 0’s.


In [25]:
# FUnction to count the words in a strong
def wordcount(strng):
    strlist1 = strng.split()
    word_dict1={}
    for i in range(len(strlist1)):
        word_dict1[strlist1[i]]=strlist1.count(strlist1[i])        
    return(pd.Series(word_dict1))

strng = input("Enter the string:")

wordcount(strng)

Enter the string:A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk


A         1
skunk     2
sat       1
on        1
a         1
stump     3
and       1
thunk     2
the       3
stunk,    1
but       1
stunk     1
dtype: int64

In [39]:
#function to add array border
def arrayborder(arr):
    n = arr.shape[0]
    m = arr.shape[1]
    horizon = np.zeros((n,1))
    vertical = np.zeros((1,m+2))
    arr_new = np.vstack([np.vstack([vertical,np.hstack([np.hstack([horizon,arr]),horizon])]),vertical])
    print("original array is: \n",arr)
    return arr_new
   
arr = np.ones((3,3))

arrayborder(arr)

original array is: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])