In [2]:
song = {"A": "do", "B":"re","C":"mi"} #defining dictionary
song

{'A': 'do', 'B': 're', 'C': 'mi'}

In [3]:
song.keys() # print keys

dict_keys(['A', 'B', 'C'])

In [4]:
len(song) # calculating length of dictionary

3

In [5]:
song["A"]="fa" # updating values in dictinary
song

{'A': 'fa', 'B': 're', 'C': 'mi'}

In [6]:
song.values() #printing values of dictionary

dict_values(['fa', 're', 'mi'])

In [7]:
"A" in song # identifyng if key is present or not in dictionary

True

In [8]:
"z"in song # identifyng if key is present or not in dictionary

False

In [9]:
del song["A"] #deleting keys in dict
print(song)

{'B': 're', 'C': 'mi'}


In [10]:
for key in song: # traversing through dict
    print(song[key])

re
mi


In [27]:
data=[1.7,"hello",4,"cat"] #defining list
data

[1.7, 'hello', 4, 'cat']

In [28]:
data[0] # accessing first element

1.7

In [29]:
data[1]=3.5 #updating value in list
data

[1.7, 3.5, 4, 'cat']

In [30]:
data[1:4] #slicing a list

[3.5, 4, 'cat']

In [31]:
len(data) # finding length of list

4

In [32]:
last=data[-1] #Accessing elements at the end of a list
print(last)

cat


In [33]:
for item in data: #Traversing through a list
    print(item)

1.7
3.5
4
cat


In [34]:
for i in range(len(data)): #Traversing a list by indices in the list
    print(data[i])

1.7
3.5
4
cat


In [35]:
6 in data

False

In [36]:
1.7 in data

True

In [37]:
del data[0] #Removing an element from a list by the item's position¶
print(data)

[3.5, 4, 'cat']


In [38]:
data.remove('cat')
print(data)

[3.5, 4]


In [42]:
a="my string is".split(" ")
print(a)

['my', 'string', 'is']


In [44]:
b=" ".join(a)
print(b)

my string is


In [45]:
import numpy as np

In [46]:
data=np.array([[1,2],[3,4]]) # defining array
data

array([[1, 2],
       [3, 4]])

In [48]:
data.dtype #Checking the array type

dtype('int32')

In [49]:
data=np.array([[1.0,2.1],[3.1,4.0]])
data

array([[1. , 2.1],
       [3.1, 4. ]])

In [50]:
data.dtype

dtype('float64')

In [52]:
data.shape #Finding the dimensions of an array

(2, 2)

In [56]:
print("rows: ", data.shape[0])#finding number of rows
print("columns: ",data.shape[1])#finding number of columns

rows:  2
columns:  2


In [57]:
data[0,0] #accessing any element of array

1.0

In [58]:
data[0,0]=5.2 #settign new vlue to an array
data

array([[5.2, 2.1],
       [3.1, 4. ]])

In [60]:
new_data=np.copy(data)
print(new_data)

[[5.2 2.1]
 [3.1 4. ]]


In [63]:
data=np.zeros((2,2)) #Creating a 2x2 array of all zeroes
print(data)

[[0. 0.]
 [0. 0.]]


In [65]:
data=np.ones((2,2))
print(data)

[[1. 1.]
 [1. 1.]]


In [84]:
data=np.array(((1,2),(3,4)))#Slicing an array
data
print(data[0:2,0])
print(data[0:1,0])
print(data[1:2,0])

print(data[0,0:2])
print(data[0,0:1])
print(data[0,1:2])

print(data[:,0])
print(data[0,:])

[1 3]
[1]
[3]
[1 2]
[1]
[2]
[1 3]
[1 2]


In [102]:
data=np.array(((1,2),(3,4)))
data
data[:,1]=[0,0]
data

array([[1, 0],
       [3, 0]])

In [103]:
print(data.transpose())

[[1 3]
 [0 0]]


In [107]:
row1=np.array(((1,2,3)))
row2=np.array(((4,5,6)))
print(np.vstack((row1,row2)))
print(np.hstack((row1,row2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [113]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
print(data.flatten())

[1 0 3 0]


In [116]:
print(data.reshape(2,2))

[[1 0]
 [3 0]]


In [121]:
import pandas as pd
companySales = {'Months':['January','February','March','April','May'], 
                'Tesla Model 5' : [900,1750,3450,1125,1620], 
                'Kia Soul EV': [117,152,171,167,129], 
                'BMW I3':[382,318,703,516,506]}
df=pd.DataFrame(companySales)
#df = pd.DataFrame(companySales,columns=["Months","Tesla Model 5","Kia Soul EV","BMW I3"])
df

Months  Tesla Model 5  Kia Soul EV  BMW I3
0   January            900          117     382
1  February           1750          152     318
2     March           3450          171     703
3     April           1125          167     516
4       May           1620          129     506

In [127]:
print("-----------first month----------")
print(df.iloc[0])
print("-----------fourth month----------")
print(df.iloc[4])

-----------first month----------
Months           January
Tesla Model 5        900
Kia Soul EV          117
BMW I3               382
Name: 0, dtype: object
-----------fourth month----------
Months            May
Tesla Model 5    1620
Kia Soul EV       129
BMW I3            506
Name: 4, dtype: object


In [136]:
print(df)
df.index=['January','February','March','April','May']
df.loc['February']

            Months  Tesla Model 5  Kia Soul EV  BMW I3
January    January            900          117     382
February  February           1750          152     318
March        March           3450          171     703
April        April           1125          167     516
May            May           1620          129     506


Months           February
Tesla Model 5        1750
Kia Soul EV           152
BMW I3                318
Name: February, dtype: object

In [138]:
print(df["BMW I3"])

January     382
February    318
March       703
April       516
May         506
Name: BMW I3, dtype: int64


In [143]:
df.drop(["BMW I3"],axis=1)

Months  Tesla Model 5  Kia Soul EV
January    January            900          117
February  February           1750          152
March        March           3450          171
April        April           1125          167
May            May           1620          129

In [150]:
df
print(df.drop(["January"]))

            Months  Tesla Model 5  Kia Soul EV  BMW I3
February  February           1750          152     318
March        March           3450          171     703
April        April           1125          167     516
May            May           1620          129     506


In [149]:
carSales = {'Tesla Model 5' : [900,1750,3450,1125,1620], 'Kia Soul EV': [117,152,171,167,129], 'BMW I3':[900,1750,3450,1125,1620]}
df_cars = pd.DataFrame(carSales,columns=["Tesla Model 5","Kia Soul EV","BMW I3"])
df_cars.index = ["January","February","March","April","May"]
print(df_cars)
print()
print('---------Deleting row "January"----------')
print()
print(df_cars.drop(["January"]))

          Tesla Model 5  Kia Soul EV  BMW I3
January             900          117     900
February           1750          152    1750
March              3450          171    3450
April              1125          167    1125
May                1620          129    1620

---------Deleting row "January"----------

          Tesla Model 5  Kia Soul EV  BMW I3
February           1750          152    1750
March              3450          171    3450
April              1125          167    1125
May                1620          129    1620


In [155]:
df_cars
print(df_cars.drop(df_cars.index[1]))

         Tesla Model 5  Kia Soul EV  BMW I3
January            900          117     900
March             3450          171    3450
April             1125          167    1125
May               1620          129    1620


In [156]:
df['Monthly Average'] = (df['Tesla Model 5'] + df['Kia Soul EV'] + df['BMW I3']) / 3
print(df)

            Months  Tesla Model 5  Kia Soul EV  BMW I3  Monthly Average
January    January            900          117     382       466.333333
February  February           1750          152     318       740.000000
March        March           3450          171     703      1441.333333
April        April           1125          167     516       602.666667
May            May           1620          129     506       751.666667


In [158]:
df["Monthly Average"] = df.mean(axis=1)
print(df)

            Months  Tesla Model 5  Kia Soul EV  BMW I3  Monthly Average
January    January            900          117     382       466.333333
February  February           1750          152     318       740.000000
March        March           3450          171     703      1441.333333
April        April           1125          167     516       602.666667
May            May           1620          129     506       751.666667


In [163]:
studentInformation = {'Students':['Marley Stevens', 'Emily Brookes','John Garcia','Steven Kosner'], 
                      'ID' : [1568921,1389012,1467892,1789021], 
                      'Grade Level': ['Sophomore','Sophomore','Freshman','Senior'], 
                      'Major':['Computer Science','Dance','English','Mathematics']}
df_students = pd.DataFrame(studentInformation,columns=["Students","ID","Grade Level","Major"])
df_students
def label_graduation(row):
    if row["Grade Level"]== "Freshman":
        return 2021
    if row["Grade Level"]=="Sophomore":
        return 2020
    if row["Grade Level"]== "Junior":
        return 2019
    if row["Grade Level"]=="Senior":
        return 2018
df_students["Graduation Year"]=df_students.apply(label_graduation,axis=1)
df_students

Students       ID Grade Level             Major  Graduation Year
0  Marley Stevens  1568921   Sophomore  Computer Science             2020
1   Emily Brookes  1389012   Sophomore             Dance             2020
2     John Garcia  1467892    Freshman           English             2021
3   Steven Kosner  1789021      Senior       Mathematics             2018

In [164]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
            'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
            'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
            'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
            'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df

Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [169]:
grouped=df.groupby("Year")
print(grouped["Points"].mean())

Year
2014    795.25
2015    769.50
2016    725.00
2017    739.00
Name: Points, dtype: float64


In [170]:
print(df.groupby("Year")["Points"].mean())

Year
2014    795.25
2015    769.50
2016    725.00
2017    739.00
Name: Points, dtype: float64


In [172]:
raw_data = {'First Name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'], 
        'Last Name': ['Miller', np.nan, 'Ali', 'Milner', 'Cooze'], 
        'Age': [42, np.nan, 36, 24, 73], 
        'Sex': ['m', np.nan, 'f', 'm', 'f'], 
        'Pre Test-score': [4, np.nan, np.nan, 2, 3],
        'Post Test-score': [25, np.nan, np.nan, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['First Name', 'Last Name', 'Age', 
                                       'Sex', 'Pre Test-score', 'Post Test-score'])

print(df)

df_no_missing=df.dropna()
df_no_missing

  First Name Last Name   Age  Sex  Pre Test-score  Post Test-score
0      Jason    Miller  42.0    m             4.0             25.0
1        NaN       NaN   NaN  NaN             NaN              NaN
2       Tina       Ali  36.0    f             NaN              NaN
3       Jake    Milner  24.0    m             2.0             62.0
4        Amy     Cooze  73.0    f             3.0             70.0


First Name Last Name   Age Sex  Pre Test-score  Post Test-score
0      Jason    Miller  42.0   m             4.0             25.0
3       Jake    Milner  24.0   m             2.0             62.0
4        Amy     Cooze  73.0   f             3.0             70.0

In [173]:
df_fill_na=df.fillna(0)
df_fill_na

First Name Last Name   Age Sex  Pre Test-score  Post Test-score
0      Jason    Miller  42.0   m             4.0             25.0
1          0         0   0.0   0             0.0              0.0
2       Tina       Ali  36.0   f             0.0              0.0
3       Jake    Milner  24.0   m             2.0             62.0
4        Amy     Cooze  73.0   f             3.0             70.0

In [174]:
df

First Name Last Name   Age  Sex  Pre Test-score  Post Test-score
0      Jason    Miller  42.0    m             4.0             25.0
1        NaN       NaN   NaN  NaN             NaN              NaN
2       Tina       Ali  36.0    f             NaN              NaN
3       Jake    Milner  24.0    m             2.0             62.0
4        Amy     Cooze  73.0    f             3.0             70.0

In [177]:
df["Pre Test-score"].fillna(df["Pre Test-score"].mean(),inplace=True)
df

First Name Last Name   Age Sex  Pre Test-score  Post Test-score
0      Jason    Miller  42.0   m             4.0             25.0
1          3         3   3.0   3             3.0              3.0
2       Tina       Ali  36.0   f             3.0              3.0
3       Jake    Milner  24.0   m             2.0             62.0
4        Amy     Cooze  73.0   f             3.0             70.0